server:
  port: 0

spring:
  application:
    name: scheduler-service   # ⭐ Config Server에서 찾을 이름

  profiles:
    # 로컬은 default, 호스팅은 dev
    active: default

  config:
    import: optional:configserver:http://localhost:8888

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always # 개발용, 운영 시 never 권장
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

imagePath:
  url: C:\stray_image

host:
  hosted: false