server:
  port: 0

spring:
  application:
    name: map-service   # ? Config Server?? ?? ??

  profiles:
    #active: default
    active: host             # ? ??? profile

  config:
    import: optional:configserver:http://config-service:8888
    #import: optional:configserver:http://localhost:8888
